[book]
authors = ["Eugene Yokota"]
language = "en"
multilingual = false
src = "src/reference"
title = "The book of sbt"

[output.html]
theme = "theme"
additional-css = ["src/reference/custom-2024.css"]
cname = "www.scala-sbt.org"

[preprocessor.variables]

[preprocessor.variables.variables]
sbt_version = "2.0.0-alpha7"
sbt_runner_version = "1.9.8"
scala3ExampleVersion = "3.3.1"
